// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1727770228);
user_pref("browser.search.region", "BJ");
user_pref("calendar.caldav.googleResync", 1727770226);
user_pref("calendar.list.sortOrder", "7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4");
user_pref("calendar.registry.7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4.calendar-main-default", true);
user_pref("calendar.registry.7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4.calendar-main-in-composite", true);
user_pref("calendar.registry.7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4.disabled", true);
user_pref("calendar.registry.7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4.name", "Mon agenda");
user_pref("calendar.registry.7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4.type", "storage");
user_pref("calendar.registry.7a8f37bc-bb4d-4e07-8e3d-a5e56c8ee8c4.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Porto-Novo");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1727770227);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-fr@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240923144135");
user_pref("extensions.lastAppVersion", "128.2.3");
user_pref("extensions.lastPlatformVersion", "128.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"8adbeeb9-9f7d-45c6-a677-914272582f2d\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ui-rdf.version", 43);
user_pref("mailnews.database.global.datastore.id", "191219aa-477c-4c52-9914-f8226ef2b9a");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.2.3");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Travail");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personnel");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "À faire");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "En attente");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1727770224);
user_pref("toolkit.telemetry.cachedClientID", "29cd238d-1a16-4865-a960-8200adb1bb2a");
user_pref("toolkit.telemetry.previousBuildID", "20240923144135");
